// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sales_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SalesModelImpl _$$SalesModelImplFromJson(Map<String, dynamic> json) =>
    _$SalesModelImpl(
      id: json['id'] as int?,
      client: json['client'] as int?,
      isMockJob: json['is_mock_job'] as bool?,
      jobCode: json['job_code'] as String?,
      quotedBy: json['quoted_by'] as String?,
      clientId: json['client_id'],
      clientName: json['client_name'] as String?,
      clientType: json['client_type'] as String?,
      paidStatus: json['paid_status'] as String?,
      date: json['date'] as String?,
      jobCardId: json['job_card_id'] as int?,
      nextService2: json['next_service_2'],
      frequency: json['frequency'] as String?,
      wasteTypeStr: json['waste_type_str'] as String?,
      typeOfWasteStrProfileName: json['type_of_waste_str_profile_name'],
      salesApproveDate: json['sales_approve_date'] as String?,
      jobCardCode: json['job_card_code'] as String?,
      createdDateTime: json['created_date_time'] == null
          ? null
          : DateTime.parse(json['created_date_time'] as String),
      jobCardKeys: json['job_card_keys'] == null
          ? null
          : JobCardKeys.fromJson(json['job_card_keys'] as Map<String, dynamic>),
      deletedStatus: json['deleted_status'] as bool?,
      tabType: json['tab_type'] as String?,
      uuid: json['uuid'] as String?,
      amount: json['amount'] as String?,
      paidAmount: json['paid_amount'] as String?,
      reoccurring: json['reoccurring'] as bool?,
      status: json['status'] as String?,
      scheduleStatus: json['schedule_status'],
      jobType: json['job_type'] as String?,
      readyForSchedule: json['ready_for_schedule'] as bool?,
      isJobThroughReccuuring: json['is_job_through_reccuuring'] as bool?,
      parentJobId: json['parent_job_id'],
      editedDateTime: json['edited_date_time'] == null
          ? null
          : DateTime.parse(json['edited_date_time'] as String),
      rescheduled: json['rescheduled'] as bool?,
      activeStatus: json['active_status'] as bool?,
      jobCardType: json['job_card_type'] as String?,
      recurringDate: json['recurring_date'] as String?,
      createdBy: json['created_by'] as String?,
      quote: json['quote'] as int?,
      jobCard: json['job_card'] as int?,
      jobComments: json['job_comments'] as List<dynamic>?,
      wonLoseStatus: json['won_lose_status'] as String?,
      scheduleId: json['schedule_id'],
      fileList: json['file_list'] as List<dynamic>?,
      clientEmail: json['client_email'] as String?,
      salePerson: json['sale_person'] as String?,
      contactNumber: json['contact_number'] as String?,
      customer: json['customer'] as String?,
      wonRejectDate: json['won_reject_date'] as String?,
      parentQuoteStatus: json['parent_quote_status'] as String?,
      mailCc: json['mail_cc'] as List<dynamic>?,
      company: json['company'],
      template: json['template'] as String?,
      templateName: json['template_name'],
      autoCreate: json['auto_create'] as int?,
      url: json['url'] as String?,
      invoiceAmt: json['invoice_amt'] as String?,
      companyName: json['company_name'] as String?,
      mailSubject: json['mail_subject'] as String?,
      mailBody: json['mail_body'] as String?,
      safetyData: json['safety_data'],
      safetyDataHtmlSend: json['safety_data_html_send'],
      salesTeamReview: json['sales_team_review'] as bool?,
      emailSendingOption: json['email_sending_option'] as bool?,
      isQuoteThroughRecurring: json['is_quote_through_recurring'] as bool?,
      recurringStatus: json['recurring_status'] as String?,
      parentQuoteId: json['parent_quote_id'],
      scopeOfWorkType: json['scope_of_work_type'] as String?,
      salesApproveDateTime: json['sales_approve_date_time'],
      quoteType: json['quote_type'] as String?,
      convertedToRecurringQuoteId: json['converted_to_recurring_quote_id'],
      employee: json['employee'] as int?,
      mailBcc: json['mail_bcc'] as List<dynamic>?,
      name: json['name'] as String?,
      won: json['won'] as int?,
      lost: json['lost'] as int?,
      pending: json['pending'] as int?,
      total: json['total'] as int?,
      profile: json['profile'] as String?,
    );

Map<String, dynamic> _$$SalesModelImplToJson(_$SalesModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'client': instance.client,
      'is_mock_job': instance.isMockJob,
      'job_code': instance.jobCode,
      'quoted_by': instance.quotedBy,
      'client_id': instance.clientId,
      'client_name': instance.clientName,
      'client_type': instance.clientType,
      'paid_status': instance.paidStatus,
      'date': instance.date,
      'job_card_id': instance.jobCardId,
      'next_service_2': instance.nextService2,
      'frequency': instance.frequency,
      'waste_type_str': instance.wasteTypeStr,
      'type_of_waste_str_profile_name': instance.typeOfWasteStrProfileName,
      'sales_approve_date': instance.salesApproveDate,
      'job_card_code': instance.jobCardCode,
      'created_date_time': instance.createdDateTime?.toIso8601String(),
      'job_card_keys': instance.jobCardKeys,
      'deleted_status': instance.deletedStatus,
      'tab_type': instance.tabType,
      'uuid': instance.uuid,
      'amount': instance.amount,
      'paid_amount': instance.paidAmount,
      'reoccurring': instance.reoccurring,
      'status': instance.status,
      'schedule_status': instance.scheduleStatus,
      'job_type': instance.jobType,
      'ready_for_schedule': instance.readyForSchedule,
      'is_job_through_reccuuring': instance.isJobThroughReccuuring,
      'parent_job_id': instance.parentJobId,
      'edited_date_time': instance.editedDateTime?.toIso8601String(),
      'rescheduled': instance.rescheduled,
      'active_status': instance.activeStatus,
      'job_card_type': instance.jobCardType,
      'recurring_date': instance.recurringDate,
      'created_by': instance.createdBy,
      'quote': instance.quote,
      'job_card': instance.jobCard,
      'job_comments': instance.jobComments,
      'won_lose_status': instance.wonLoseStatus,
      'schedule_id': instance.scheduleId,
      'file_list': instance.fileList,
      'client_email': instance.clientEmail,
      'sale_person': instance.salePerson,
      'contact_number': instance.contactNumber,
      'customer': instance.customer,
      'won_reject_date': instance.wonRejectDate,
      'parent_quote_status': instance.parentQuoteStatus,
      'mail_cc': instance.mailCc,
      'company': instance.company,
      'template': instance.template,
      'template_name': instance.templateName,
      'auto_create': instance.autoCreate,
      'url': instance.url,
      'invoice_amt': instance.invoiceAmt,
      'company_name': instance.companyName,
      'mail_subject': instance.mailSubject,
      'mail_body': instance.mailBody,
      'safety_data': instance.safetyData,
      'safety_data_html_send': instance.safetyDataHtmlSend,
      'sales_team_review': instance.salesTeamReview,
      'email_sending_option': instance.emailSendingOption,
      'is_quote_through_recurring': instance.isQuoteThroughRecurring,
      'recurring_status': instance.recurringStatus,
      'parent_quote_id': instance.parentQuoteId,
      'scope_of_work_type': instance.scopeOfWorkType,
      'sales_approve_date_time': instance.salesApproveDateTime,
      'quote_type': instance.quoteType,
      'converted_to_recurring_quote_id': instance.convertedToRecurringQuoteId,
      'employee': instance.employee,
      'mail_bcc': instance.mailBcc,
      'name': instance.name,
      'won': instance.won,
      'lost': instance.lost,
      'pending': instance.pending,
      'total': instance.total,
      'profile': instance.profile,
    };
