// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

import 'folder.dart';

part 'vehicle_model.freezed.dart';
part 'vehicle_model.g.dart';

@freezed
class VehicleModel with _$VehicleModel {
  factory VehicleModel({
    int? id,
    @JsonKey(name: 'image_thumbnail') String? imageThumbnail,
    String? image1,
    @JsonKey(name: 'multiple_images') List<dynamic>? multipleImages,
    @JsonKey(name: 'tab_type') String? tabType,
    @JsonKey(name: 'vehicle_type') String? vehicleType,
    @JsonKey(name: 'active_status') bool? activeStatus,
    @JsonKey(name: 'previous_rego') dynamic previousRego,
    String? registration,
    String? types,
    dynamic year,
    String? transmission,
    String? fuel,
    String? height,
    String? width,
    String? length,
    String? litres,
    @JsonKey(name: 'vin_number') String? vinNumber,
    String? axies,
    @JsonKey(name: 'due_rego') String? dueRego,
    @JsonKey(name: 'engine_numbers') String? engineNumbers,
    @JsonKey(name: 'e_tag') String? eTag,
    String? insurance,
    @JsonKey(name: 'fuel_card') String? fuelCard,
    String? fbt,
    bool? action,
    String? image2,
    String? image3,
    @JsonKey(name: 'preinspection_required') bool? preinspectionRequired,
    @JsonKey(name: 'created_date_time') DateTime? createdDateTime,
    @JsonKey(name: 'edited_date_time') DateTime? editedDateTime,
    String? date,
    String? time,
    @JsonKey(name: 'truck_rego') String? truckRego,
    @JsonKey(name: 'current_reading_before') String? currentReadingBefore,
    @JsonKey(name: 'reading_after_filling') String? readingAfterFilling,
    @JsonKey(name: 'filled_by') String? filledBy,
    @JsonKey(name: 'volume_usedIn_liter') String? volumeUsedInLiter,
    int? vehicle,
    int? folder,
    String? description,
    @JsonKey(name: 'invoice_date') String? invoiceDate,
    @JsonKey(name: 'service_date') String? serviceDate,
    String? ometer,
    @JsonKey(name: 'invoice_number') int? invoiceNumber,
    @JsonKey(name: 'service_provided') String? serviceProvided,
    String? hours,
    @JsonKey(name: 'l_cost') String? lCost,
    @JsonKey(name: 's_part') String? sPart,
    String? gst,
    @JsonKey(name: 'total_cost') String? totalCost,
    @JsonKey(name: 'date_time') DateTime? dateTime,
    int? odometer,
    @JsonKey(name: 'odometdriver_signature') String? odometdriverSignature,
    @JsonKey(name: 'hour_meter_start') String? hourMeterStart,
    // ignore: invalid_annotation_target
    @JsonKey(name: 'fit_for_work') bool? fitForWork,
    @JsonKey(name: 'Valid_driving_license') bool? validDrivingLicense,
    @JsonKey(name: 'appropriate_ppe') bool? appropriatePpe,
    @JsonKey(name: 'engine_oil_level') bool? engineOilLevel,
    @JsonKey(name: 'warning_system') bool? warningSystem,
    bool? steering,
    @JsonKey(name: 'safety_emerg_stop') bool? safetyEmergStop,
    @JsonKey(name: 'handbreak_alarm') bool? handbreakAlarm,
    @JsonKey(name: 'pto_vacpump') bool? ptoVacpump,
    bool? horn,
    @JsonKey(name: 'rev_alarm_camera') bool? revAlarmCamera,
    @JsonKey(name: 'lights_head') bool? lightsHead,
    @JsonKey(name: 'lights_tail') bool? lightsTail,
    @JsonKey(name: 'light_beacons') bool? lightBeacons,
    @JsonKey(name: 'hazard_light') bool? hazardLight,
    @JsonKey(name: 'rims_wheelnut') bool? rimsWheelnut,
    bool? coolant,
    bool? wheels,
    @JsonKey(name: 'mirror_windowscreen') bool? mirrorWindowscreen,
    @JsonKey(name: 'structure_bodywork') bool? structureBodywork,
    bool? wipers,
    @JsonKey(name: 'fuel_levelpump') bool? fuelLevelpump,
    @JsonKey(name: 'fuel_leveltruck') bool? fuelLeveltruck,
    @JsonKey(name: 'seat_seatbelt') bool? seatSeatbelt,
    @JsonKey(name: 'parkbrake_trailer') bool? parkbrakeTrailer,
    @JsonKey(name: 'foot_brake') bool? footBrake,
    bool? electrical,
    @JsonKey(name: 'pin_retainers') bool? pinRetainers,
    bool? hoses,
    bool? fittings,
    @JsonKey(name: 'first_aid_kit') bool? firstAidKit,
    bool? ppe,
    @JsonKey(name: 'fire_extinguisher_date') String? fireExtinguisherDate,
    @JsonKey(name: 'fire_extinguisher') bool? fireExtinguisher,
    @JsonKey(name: 'house_keeping') bool? houseKeeping,
    @JsonKey(name: 'garden_hose') bool? gardenHose,
    @JsonKey(name: 'gatic_lifters') bool? gaticLifters,
    @JsonKey(name: 'bucket_rags') bool? bucketRags,
    @JsonKey(name: 'spill_kit') dynamic spillKit,
    @JsonKey(name: 'action_taken') dynamic actionTaken,
    @JsonKey(name: 'authorized_by') dynamic authorizedBy,
    @JsonKey(name: 'safe_ready_to_operate') dynamic safeReadyToOperate,
    @JsonKey(name: 'reported_faults') dynamic reportedFaults,
    @JsonKey(name: 'reviewed_form') dynamic reviewedForm,
    dynamic corrected,
    @JsonKey(name: 'scheduled_for_repair') dynamic scheduledForRepair,
    @JsonKey(name: 'no_action') dynamic noAction,
    @JsonKey(name: 'do_not_affect_safe_operation')
    bool? doNotAffectSafeOperation,
    String? name,
    dynamic signature,
    @JsonKey(name: 'date_now') dynamic dateNow,
    @JsonKey(name: 'reported_fault_string') dynamic reportedFaultString,
    @JsonKey(name: 'driver_name') int? driverName,
    List<Folder>? folders,
    @JsonKey(name: 'parent_folder') int? parentFolder,
  }) = _VehicleModel;

  factory VehicleModel.fromJson(Map<String, dynamic> json) =>
      _$VehicleModelFromJson(json);
}
