// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'truckpage_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CmnvehiclepageModelImpl _$$CmnvehiclepageModelImplFromJson(
        Map<String, dynamic> json) =>
    _$CmnvehiclepageModelImpl(
      odometer: json['odometer'] as int?,
      id: json['id'] as int?,
      imageThumbnail: json['imageThumbnail'] as String?,
      image1: json['image1'] as String?,
      multipleImages: json['multipleImages'] as List<dynamic>?,
      tabType: json['tabType'] as String?,
      vehicleType: json['vehicleType'] as String?,
      activeStatus: json['activeStatus'] as bool?,
      previousRego: json['previousRego'],
      registration: json['registration'] as String?,
      types: json['types'] as String?,
      year: json['year'] as int?,
      transmission: json['transmission'] as String?,
      fuel: json['fuel'] as String?,
      height: json['height'] as String?,
      width: json['width'] as String?,
      length: json['length'] as String?,
      litres: json['litres'] as String?,
      vinNumber: json['vinNumber'] as String?,
      axies: json['axies'] as String?,
      dueRego: json['dueRego'] as String?,
      engineNumbers: json['engineNumbers'] as String?,
      eTag: json['eTag'] as String?,
      insurance: json['insurance'] as String?,
      fuelCard: json['fuelCard'] as String?,
      fbt: json['fbt'] as String?,
      action: json['action'] as bool?,
      image2: json['image2'] as String?,
      image3: json['image3'] as String?,
      preinspectionRequired: json['preinspectionRequired'] as bool?,
      createdDateTime: json['createdDateTime'] as String?,
      editedDateTime: json['editedDateTime'] as String?,
      description: json['description'] as String?,
      date_time: json['date_time'] as String?,
      driver_name: json['driver_name'] as int?,
      service_provided: json['service_provided'] as String?,
      l_cost: json['l_cost'] as String?,
      s_part: json['s_part'] as String?,
      total_cost: json['total_cost'] as String?,
    );

Map<String, dynamic> _$$CmnvehiclepageModelImplToJson(
        _$CmnvehiclepageModelImpl instance) =>
    <String, dynamic>{
      'odometer': instance.odometer,
      'id': instance.id,
      'imageThumbnail': instance.imageThumbnail,
      'image1': instance.image1,
      'multipleImages': instance.multipleImages,
      'tabType': instance.tabType,
      'vehicleType': instance.vehicleType,
      'activeStatus': instance.activeStatus,
      'previousRego': instance.previousRego,
      'registration': instance.registration,
      'types': instance.types,
      'year': instance.year,
      'transmission': instance.transmission,
      'fuel': instance.fuel,
      'height': instance.height,
      'width': instance.width,
      'length': instance.length,
      'litres': instance.litres,
      'vinNumber': instance.vinNumber,
      'axies': instance.axies,
      'dueRego': instance.dueRego,
      'engineNumbers': instance.engineNumbers,
      'eTag': instance.eTag,
      'insurance': instance.insurance,
      'fuelCard': instance.fuelCard,
      'fbt': instance.fbt,
      'action': instance.action,
      'image2': instance.image2,
      'image3': instance.image3,
      'preinspectionRequired': instance.preinspectionRequired,
      'createdDateTime': instance.createdDateTime,
      'editedDateTime': instance.editedDateTime,
      'description': instance.description,
      'date_time': instance.date_time,
      'driver_name': instance.driver_name,
      'service_provided': instance.service_provided,
      'l_cost': instance.l_cost,
      's_part': instance.s_part,
      'total_cost': instance.total_cost,
    };
