// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'client.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ClientImpl _$$ClientImplFromJson(Map<String, dynamic> json) => _$ClientImpl(
      id: json['id'] as num?,
      tabType: json['tab_type'] as String?,
      serviceList: (json['service_list'] as List<dynamic>?)
          ?.map((e) => ServiceList.fromJson(e as Map<String, dynamic>))
          .toList(),
      paymentDetails: json['payment_details'] as String?,
      companyName: json['company_name'],
      companyAddress: json['company_address'],
      siteName: json['site_name'] as String?,
      siteSuburb: json['site_suburb'],
      sitePostCode: json['site_post_code'] as String?,
      siteAddress: json['site_address'] as String?,
      siteContactEmail: json['site_contact_email'] as String?,
      siteContactPhone: json['site_contact_phone'] as String?,
      siteContactMob: json['site_contact_mob'] as String?,
      building: json['building'],
      companyEmail: json['company_email'],
      companyContactNumber: json['company_contact_number'],
      siteContactPerson: json['site_contact_person'] as String?,
      accessRestriction: json['access_restriction'] as String?,
      tcRequired: json['tc_required'] as bool?,
      tcRequiredFile: json['tc_required_file'],
      wasteDataForm: json['waste_data_form'] as bool?,
      dataFormRequiredFile: json['data_form_required_file'],
      accessHeight: json['access_height'] as String?,
      keyRequired: json['key_required'] as bool?,
      securityRequired: json['security_required'] as bool?,
      inductionRequired: json['induction_required'] as bool?,
      contactName: json['contact_name'],
      phoneNumber: json['phone_number'],
      price: json['price'],
      accountStatus: json['account_status'],
      salesPerson: json['sales_person'] as String?,
      typeOfInduction: json['type_of_induction'] as String?,
      pitDistanceFromTruckLocation:
          json['pit_distance_from_truck_location'] as String?,
      waterTapLocation: json['water_tap_location'] as String?,
      gumyRequired: json['gumy_required'] as bool?,
      gurneyRequired: json['gurney_required'] as bool?,
      weighBridgeRequired: json['weigh_bridge_required'] as String?,
      weighBridgeRequiredFile: json['weigh_bridge_required_file'],
      estimatedJobDuration: json['estimated_job_duration'] as String?,
      timeForService: json['time_for_service'] as String?,
      noAndTypePalletToBeExchanged:
          json['no_and_type_pallet_to_be_exchanged'] as String?,
      additionalInformation: json['additional_information'] as String?,
      capacity: json['capacity'] as String?,
      barcode: json['barcode'] as String?,
      jobStatus: json['job_status'],
      pitLocation: json['pit_location'] as String?,
      safetyDataSheetRequired: json['safety_data_sheet_required'] as String?,
      safetyDataSheetFile: json['safety_data_sheet_file'],
      chemistApproval: json['chemist_approval'] as String?,
      chemistApprovalFile: json['chemist_approval_file'],
      confinedSpace: json['confined_space'] as bool?,
      numberOfTrucksRequired: json['number_of_trucks_required'] as String?,
      specificPpeReqired: json['specific_ppe_reqired'] as bool?,
      serviceTime: json['service_time'],
      ifYesSpecify: json['if_yes_specify'],
      completedBy: json['completed_by'],
      date:
          json['date'] == null ? null : DateTime.parse(json['date'] as String),
      tcRequiredComment: json['tc_required_comment'] as String?,
      comment: json['comment'],
      additionalImages: json['additional_images'] as String?,
      smokeAlarms: json['smoke_alarms'] as String?,
      jobCardName: json['job_card_name'],
      typeOfWasteStr: json['type_of_waste_str'] as String?,
      childSiteId: json['child_site_id'] as String?,
      createdDateTime: json['created_date_time'] == null
          ? null
          : DateTime.parse(json['created_date_time'] as String),
      editedDateTime: json['edited_date_time'] == null
          ? null
          : DateTime.parse(json['edited_date_time'] as String),
      reoccurring: json['reoccurring'] as bool?,
      frequency: json['frequency'] as String?,
      latitude: json['latitude'] as String?,
      longitude: json['longitude'] as String?,
      manifest: json['manifest'] as String?,
      manifestFile: json['manifest_file'],
      specificPpeRequiredComment:
          json['specific_ppe_required_comment'] as String?,
      purchaseComment: json['purchase_comment'] as String?,
      outsourcedJob: json['outsourced_job'] as bool?,
      dailySchedule: json['daily_schedule'] as bool?,
      scheduleDays: json['schedule_days'] as String?,
      industryType: json['industry_type'] as num?,
      inDraft: json['in_draft'] as bool?,
      keyRequiredNew: json['key_required_new'] as String?,
      photoRequired: json['photo_required'] as bool?,
      photoRequiredText: json['photo_required_text'] as String?,
      certificateOfDestructionRequired:
          json['certificate_of_destruction_required'] as bool?,
      certificateOfDestructionRequiredText:
          json['certificate_of_destruction_required_text'] as String?,
      wastePackagedMethod: json['waste_packaged_method'] as String?,
      volumeExpected: json['volume_expected'] as String?,
      numberOfLoadsExpected: json['number_of_loads_expected'] as String?,
      sampleOfWasteToBeCollected:
          json['sample_of_waste_to_be_collected'] as bool?,
      sampleOfWasteToBeCollectedText:
          json['sample_of_waste_to_be_collected_text'] as String?,
      estimatedDatetimeOfDisposal:
          json['estimated_datetime_of_disposal'] as String?,
      flowMeterRequired: json['flow_meter_required'] as bool?,
      customerName: json['customer_name'] as String?,
      customerAddress: json['customer_address'] as String?,
      customerContactEmail: json['customer_contact_email'] as String?,
      customerContactPhone: json['customer_contact_phone'] as String?,
      customerContactMob: json['customer_contact_mob'] as String?,
      additionalPhoneNumber: json['additional_phone_number'] == null
          ? null
          : AdditionalPhoneNumber.fromJson(
              json['additional_phone_number'] as Map<String, dynamic>),
      additionalEmail: json['additional_email'] == null
          ? null
          : AdditionalEmail.fromJson(
              json['additional_email'] as Map<String, dynamic>),
      addInfoButton: json['add_info_button'] as String?,
      destructionCertificateUnread:
          json['destruction_certificate_unread'] as bool?,
      quote: json['quote'] as num?,
      client: json['client'] as num?,
      tcRequiredMultipleFile:
          json['tc_required_multiple_file'] as List<dynamic>?,
      dataFormRequiredMultipleFile:
          json['data_form_required_multiple_file'] as List<dynamic>?,
      weighBridgeRequiredMultipleFile:
          json['weigh_bridge_required_multiple_file'] as List<dynamic>?,
      safetyDataSheetFiles: json['safety_data_sheet_files'] as List<dynamic>?,
      chemistApprovalMultipleFile:
          json['chemist_approval_multiple_file'] as List<dynamic>?,
      manifestMultipleFile: json['manifest_multiple_file'] as List<dynamic>?,
      purchaseOrder: json['purchase_order'] as List<dynamic>?,
    );

Map<String, dynamic> _$$ClientImplToJson(_$ClientImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'tab_type': instance.tabType,
      'service_list': instance.serviceList,
      'payment_details': instance.paymentDetails,
      'company_name': instance.companyName,
      'company_address': instance.companyAddress,
      'site_name': instance.siteName,
      'site_suburb': instance.siteSuburb,
      'site_post_code': instance.sitePostCode,
      'site_address': instance.siteAddress,
      'site_contact_email': instance.siteContactEmail,
      'site_contact_phone': instance.siteContactPhone,
      'site_contact_mob': instance.siteContactMob,
      'building': instance.building,
      'company_email': instance.companyEmail,
      'company_contact_number': instance.companyContactNumber,
      'site_contact_person': instance.siteContactPerson,
      'access_restriction': instance.accessRestriction,
      'tc_required': instance.tcRequired,
      'tc_required_file': instance.tcRequiredFile,
      'waste_data_form': instance.wasteDataForm,
      'data_form_required_file': instance.dataFormRequiredFile,
      'access_height': instance.accessHeight,
      'key_required': instance.keyRequired,
      'security_required': instance.securityRequired,
      'induction_required': instance.inductionRequired,
      'contact_name': instance.contactName,
      'phone_number': instance.phoneNumber,
      'price': instance.price,
      'account_status': instance.accountStatus,
      'sales_person': instance.salesPerson,
      'type_of_induction': instance.typeOfInduction,
      'pit_distance_from_truck_location': instance.pitDistanceFromTruckLocation,
      'water_tap_location': instance.waterTapLocation,
      'gumy_required': instance.gumyRequired,
      'gurney_required': instance.gurneyRequired,
      'weigh_bridge_required': instance.weighBridgeRequired,
      'weigh_bridge_required_file': instance.weighBridgeRequiredFile,
      'estimated_job_duration': instance.estimatedJobDuration,
      'time_for_service': instance.timeForService,
      'no_and_type_pallet_to_be_exchanged':
          instance.noAndTypePalletToBeExchanged,
      'additional_information': instance.additionalInformation,
      'capacity': instance.capacity,
      'barcode': instance.barcode,
      'job_status': instance.jobStatus,
      'pit_location': instance.pitLocation,
      'safety_data_sheet_required': instance.safetyDataSheetRequired,
      'safety_data_sheet_file': instance.safetyDataSheetFile,
      'chemist_approval': instance.chemistApproval,
      'chemist_approval_file': instance.chemistApprovalFile,
      'confined_space': instance.confinedSpace,
      'number_of_trucks_required': instance.numberOfTrucksRequired,
      'specific_ppe_reqired': instance.specificPpeReqired,
      'service_time': instance.serviceTime,
      'if_yes_specify': instance.ifYesSpecify,
      'completed_by': instance.completedBy,
      'date': instance.date?.toIso8601String(),
      'tc_required_comment': instance.tcRequiredComment,
      'comment': instance.comment,
      'additional_images': instance.additionalImages,
      'smoke_alarms': instance.smokeAlarms,
      'job_card_name': instance.jobCardName,
      'type_of_waste_str': instance.typeOfWasteStr,
      'child_site_id': instance.childSiteId,
      'created_date_time': instance.createdDateTime?.toIso8601String(),
      'edited_date_time': instance.editedDateTime?.toIso8601String(),
      'reoccurring': instance.reoccurring,
      'frequency': instance.frequency,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'manifest': instance.manifest,
      'manifest_file': instance.manifestFile,
      'specific_ppe_required_comment': instance.specificPpeRequiredComment,
      'purchase_comment': instance.purchaseComment,
      'outsourced_job': instance.outsourcedJob,
      'daily_schedule': instance.dailySchedule,
      'schedule_days': instance.scheduleDays,
      'industry_type': instance.industryType,
      'in_draft': instance.inDraft,
      'key_required_new': instance.keyRequiredNew,
      'photo_required': instance.photoRequired,
      'photo_required_text': instance.photoRequiredText,
      'certificate_of_destruction_required':
          instance.certificateOfDestructionRequired,
      'certificate_of_destruction_required_text':
          instance.certificateOfDestructionRequiredText,
      'waste_packaged_method': instance.wastePackagedMethod,
      'volume_expected': instance.volumeExpected,
      'number_of_loads_expected': instance.numberOfLoadsExpected,
      'sample_of_waste_to_be_collected': instance.sampleOfWasteToBeCollected,
      'sample_of_waste_to_be_collected_text':
          instance.sampleOfWasteToBeCollectedText,
      'estimated_datetime_of_disposal': instance.estimatedDatetimeOfDisposal,
      'flow_meter_required': instance.flowMeterRequired,
      'customer_name': instance.customerName,
      'customer_address': instance.customerAddress,
      'customer_contact_email': instance.customerContactEmail,
      'customer_contact_phone': instance.customerContactPhone,
      'customer_contact_mob': instance.customerContactMob,
      'additional_phone_number': instance.additionalPhoneNumber,
      'additional_email': instance.additionalEmail,
      'add_info_button': instance.addInfoButton,
      'destruction_certificate_unread': instance.destructionCertificateUnread,
      'quote': instance.quote,
      'client': instance.client,
      'tc_required_multiple_file': instance.tcRequiredMultipleFile,
      'data_form_required_multiple_file': instance.dataFormRequiredMultipleFile,
      'weigh_bridge_required_multiple_file':
          instance.weighBridgeRequiredMultipleFile,
      'safety_data_sheet_files': instance.safetyDataSheetFiles,
      'chemist_approval_multiple_file': instance.chemistApprovalMultipleFile,
      'manifest_multiple_file': instance.manifestMultipleFile,
      'purchase_order': instance.purchaseOrder,
    };
